included:
    - ./Sources
    - ./Tests
    - ./Tools
    - ./Utility

function_parameter_count:
    warning: 8
    error: 25

opt_in_rules:
    - first_where
    - sorted_first_last
    # - missing_docs

disabled_rules:
    - mark
    - force_cast
    - force_try
    - todo
    - line_length
    - file_length
    - function_body_length
    - type_body_length
    - identifier_name
    - nesting
    - cyclomatic_complexity
    - trailing_comma
    - large_tuple
